### ISSUE TITLE
hrnet person tracking issues

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-core#106]
hrnet is less robust in person tracking than openpose. let's dig in.

some example sessions here https://docs.google.com/document/d/1joyR2rTktXHykutDNdjHh_VeshmC7IbvTAVcoICFAVg/edit?usp=sharing

@antoinefalisse happy to hack this with you sometime if you'd like

**Comment by antoinefalisse** [comment]
Might be good to chat with Yoni about person detection tracking. We could potentially swap the algo.

**Comment by antoinefalisse** [comment]
Closed with #114
