### ISSUE TITLE
i want to get phone Model automatically in local

### ISSUE THREAD

**Issue by dkssud8150** [stanfordnmbl/opencap-core#115]
hello, i'm brian.

i want to get phone model automatically in my computer.

when we use your app, maybe the phone model can be saved in your server. 

in my case, i wanna use your code to our project in local. but i can't get our phone model that take the video when i implement opencap-core code.

how can i get this?

thanks

**Comment by suhlrich** [comment]
the phone model is stored in the sessionMetadata.yaml which you get when you download data. There is a mapping between what is in that yaml to phone models here: https://stackoverflow.com/questions/26028918/how-to-determine-the-current-iphone-device-model
