### ISSUE TITLE
Broken links on opencap.ai site

### ISSUE THREAD

**Issue by jenhicks** [stanfordnmbl/opencap-core#12]
On this page, the links to "contact us" are broken: https://www.opencap.ai/troubleshooting

Could point here (https://www.opencap.ai/#contact), but might be better to change the text to "visit our forum" and link to the simk forum.

**Comment by jenhicks** [comment]
Thanks! The forum is not super prominent. Maybe in the contact page on the left side you could add an image of it or otherwise help it stand out?

**Comment by antoinefalisse** [comment]
Good idea, will do.
