### ISSUE TITLE
Create a custom session with custom cameras

### ISSUE THREAD

**Issue by BousqueThomas** [stanfordnmbl/opencap-core#151]
Hi ! 

Thank you for the amazing work you've done with OpenCap :-)

I'm currently trying to use OpenCap in a custom setup with custom cameras (other than iPhone) plugged in USB to my computer. Thus, I'm trying to find a way to properly capture a session in the correct format using these two custom cameras, but I have not find a solution yet.

At the moment, I'm carefully reading the utilsServer.py file, as I guess that the solution to my problem lies in modifying/customizing one (or several) functions of this file, but I don't know if I'm wrong. A few guidelines would be greately welcomed :-)

Thank you for your help !

**Comment by antoinefalisse** [comment]
Hi @BousqueThomas could I ask you to post your question on the forum? It is a better place than here for discussing your use case: https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=2385&pluginname=phpBB

Thanks, Antoine

**Comment by BousqueThomas** [comment]
Hi @antoinefalisse !
Yes, of course. I have submitted my question there.

Thanks. :)
