### ISSUE TITLE
OpenCap Data Sharing Issue

### ISSUE THREAD

**Issue by sophieburton098** [stanfordnmbl/opencap-core#152]
There currently seems to be an issue with the data-sharing option when trying to collect data. The data-sharing agreement options do not appear and, therefore cannot be selected, and subsequently, no static trials can occur. 

<img width="684" alt="Screenshot 2024-04-30 at 13 41 33" src="https://github.com/stanfordnmbl/opencap-core/assets/168550205/ccb2356c-4ad0-4bb7-9423-d4c14be2cb51">

**Comment by antoinefalisse** [comment]
Problem solved. Thanks.
