### ISSUE TITLE
Data sharing agreement unavailable - unable to record

### ISSUE THREAD

**Issue by JasperVerheul** [stanfordnmbl/opencap-core#153]
The data sharing agreement option is currently unavailable. Therefore, no option can be selected preventing the recording of a static trial or any subsequent dynamic trials. This has been tried on multiple devices.
![Capture](https://github.com/stanfordnmbl/opencap-core/assets/100410818/1641d2b8-7aca-48b8-9b0e-3a3136a9a9f8)

**Comment by antoinefalisse** [comment]
Problem solved.
