### ISSUE TITLE
OpenCap recorded sideways

### ISSUE THREAD

**Issue by kguardino** [stanfordnmbl/opencap-core#179]
Ipads and participant was upright but the skeleton is recorded as sideways, parallel to the checkerboard floor. Can we fix this after the fact? can i make sure this doesn't happen again? I didn't change anything about the way I usually run the study visit.
<img width="558" alt="Screenshot 2024-07-11 at 11 26 57 AM" src="https://github.com/stanfordnmbl/opencap-core/assets/175350163/ae916145-1f54-4f8e-8826-b9f38958ffce">

**Comment by antoinefalisse** [comment]
@kguardino please post your question on the forum and share the session ID: https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=2385&pluginname=phpBB. We will respond promptly. Thanks
