### ISSUE TITLE
Pose Detection Timed Out Error

### ISSUE THREAD

**Issue by sophieburton098** [stanfordnmbl/opencap-core#181]
<img width="686" alt="Screenshot 2024-08-05 at 14 43 20" src="https://github.com/user-attachments/assets/792f5ebe-602b-42ac-8d61-d8968f47cdae">

Please take a look at the error above. Any extra support on this would be truly appreciated.

**Comment by AlbertoCasasOrtiz** [comment]
This error is raised in these two lines of code depending on the pose detection algorithm used. 

- https://github.com/stanfordnmbl/opencap-core/blob/6cf210e3738cad66d20827d577182f5323a643b2/utilsDetector.py#L316
- https://github.com/stanfordnmbl/opencap-core/blob/6cf210e3738cad66d20827d577182f5323a643b2/utilsDetector.py#L205

Looks like the current time limit for pose detection is 60 minutes (60*60 in the code). Do you think we should increase those times @carmichaelong?

**Comment by AlbertoCasasOrtiz** [comment]
@sophieburton098 Could you share the URL or ID of your sessions throwing this error so we can look deeper into this?

As a temporary solution we can put your trials again into the queue so they are reprocessed. Would this work for you?

**Comment by sophieburton098** [comment]
Hi Alberto,


Here are the session IDs.

00ff5ad0-1a4a-40c3-b473-300b33e95380 - trial name: P88_10kph_01

8b8900dd-c4ab-4516-be8c-9ae8b7f36314 - trial name: P89_10kph

26bec39a-b7b8-4435-afcc-5cbb8d40aa90 - trial name: P90_10kph

And yes, pop them in the queue, that would be great.


Kind Regards

Sophie Burton

__________________________________________________________________________

My workday may look different from your workday.

Please do not feel obligated to respond outside of your normal working hours.



Senior Lecturer in Sport and Exercise Biomechanics | Uwch Darlithydd mewn Biomecaneg Chwaraeon ac Ymarfer Corff

Research Associate (PhD candidate) | Cydymaith Ymchwil (ymgeisydd PhD)

Cardiff School of Sport and Health Sciences | Ysgol Chwaraeon a Gwyddorau Iechyd Caerdydd

Cardiff Metropolitan University | Prifysgol Metropolitan Caerdydd

Cyncoed Campus | Campws Cyncoed

Cardiff | Caerdydd  |   CF23 6XD

________________________________

**Comment by AlbertoCasasOrtiz** [comment]
Hi. I just pop them in the queue and everything has been reprocessed successfully! Feel free to ask any more questions and to close the issue if this solves your problem.

**Comment by sophieburton098** [comment]
Fantastic news. This issue has cropped up again with two further sessions completed today. Could these also be reprocessed? I have another four sessions tomorrow, so this may crop up again (if so, I will post the session IDs here also). Below are the two session IDs that have incurred the same issue and need to be 

b11fdff8-aaf3-40b5-97ff-dd555b47f888 - trial name: P91_10kph_01

4dd0d4b0-c547-4faf-802d-0a006cabbbb7 - trial name: P92_08kph

**Comment by AlbertoCasasOrtiz** [comment]
Everything should be solved now

**Comment by sophieburton098** [comment]
[celebrate]     Burton, Sophie reacted to your message:
________________________________
