### ISSUE TITLE
Intrinsics

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-core#183]
Mapping between iOS device model and internal model name https://stackoverflow.com/questions/26028918/how-to-determine-the-current-iphone-device-model

**Comment by mattpetrucci** [comment]
- Update intrinsics for iPad Air 2024 (same as last model).
- Need to create new intrinsics for iPad Pro (M4)

**Comment by mattpetrucci** [comment]
Added pull request to address iPad Air models: https://github.com/stanfordnmbl/opencap-core/pull/195

**Comment by mattpetrucci** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OpenCap intrinsics](https://trello.com/c/wSqMZhlD/67-opencap-intrinsics)
