### ISSUE TITLE
Coordinate systems

### ISSUE THREAD

**Issue by mureva** [stanfordnmbl/opencap-core#20]
I have tools for projecting point clouds or 3D models onto images, and I wanted to use those to visualise your marker reconstructions, and OpenSim solves, back over the images.

I'm able to load the calibration data from your pickle files, and do a basic sanity check that that makes sense (reconstruct a 3D point from a couple of manually annotated image features between my views) - however if I then render the markers from any of the .trc files into the images, they are not in a compatible coordinate system. I've also done a simple python script to draw the camera positions inferred from the calibration and the point cloud from the markers - making it all the more obvious that the coordinate systems do not match - the point cloud of the person does not get drawn where the cameras are looking.

Can you explain the coordinate systems you use, and what transformations are needed to move between them?

Here's a simple visualisation:
Camera positions shown as grey circles with axes, x-red, y-green, z-blue (camera appears to look along +z), markers from .trc file give blue circles, origin shown with axes.
![test0](https://user-images.githubusercontent.com/40495062/206732134-b833c2b2-0bf9-4260-ac9b-1dd3049c20a3.png)

**Comment by antoinefalisse** [comment]
Hey @mureva, the markers are rotated to match the OpenSim conventions. You can find the rotations [here](https://github.com/stanfordnmbl/opencap-core/blob/main/main.py#L229). When you download you OpenCap data, there is a yaml file sessionMetadata where you can find checkerboard: placement, which is used [here](https://github.com/stanfordnmbl/opencap-core/blob/main/main.py#L231). See also [here ](https://github.com/stanfordnmbl/opencap-core/blob/main/utilsChecker.py#L2753)where we actually rotate the data. Hope it help, let us know for questions.

**Comment by mureva** [comment]
Thanks,
I had pretty much resolved the rotations as I was expecting them - I seem to be left with a vertical translation of about 200 mm however - I'm guessing it comes from you re-setting the ground plane somewhere but so far I've failed to grep my way to where you're doing that.

**Comment by antoinefalisse** [comment]
Yes, we add an offset in vertical translation such that the marker with the lowest vertical position across all time frames is is in contact with the ground (ie, the lowest vertical position is 0). See [here](https://github.com/stanfordnmbl/opencap-core/blob/main/main.py#L352). If you reprocess your data locally and turn [the flag offset to False](https://github.com/stanfordnmbl/opencap-core/blob/main/main.py#L38), then no offset will be added.
