### ISSUE TITLE
Recorded Trials are not processing 

### ISSUE THREAD

**Issue by Sitarman1** [stanfordnmbl/opencap-core#218]
Hey guys, i recorded some Trials Yesterday and now somehow my Trials are not loading and processing so i can not analyse my Data in Opencap. Did somebody have similar issues and how could i try to fix it?

**Comment by antoinefalisse** [comment]
Hey, there is super high demand at the moment. Processing might take longer than usual. If there is an orange dot next to the trial it means it is in the queue and should be processed.

**Comment by antoinefalisse** [comment]
For more infor, please consult the forum: https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=2385&pluginname=phpBB
