### ISSUE TITLE
More expressive shoulder

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-core#36]
Problems:
1) jumps between solutions giving unrealistic kinematics
2) un-modeled scapular motion causes artifact torso motion and likely bad arm kinematics

Approach options
1) add Ajay's model to ours, scale the ellipsoid by torso scale factors (not sure if it auto-scales with the body). For UE dynamics, could just use ID, for DC, we could map glenohumeral kinematics onto a 6dof simple shoulder.
2) 6dof shoulder with tracking of 0 for translations. Downside -> visualization will be poor.

My plan is to try #2 first since much simpler. Thoughts @antoinefalisse?

Todo for sure
1) add tracking of 0 for rotations

Test session:https://app.opencap.ai/session/ea0cfa3f-58bc-4ead-a3bc-12e17a7d8884

**Comment by antoinefalisse** [comment]
With approach 1, how would we track the scapula motion? I would start with approach 2 to test how that goes.
