### ISSUE TITLE
autoscaling

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-core#45]
Scaling rule:
- if nInstances == 0 and len(queue) > 0 ---> nInstances = 1
- if len(queue)) > 5 and nInstances >1 ---> nInstances += 1

-evaluate scaling rule in API every so often (cron job?)
-Increase number of instances if needed, can use boto3 [cmds](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/autoscaling/client/set_desired_capacity.html)
-to scale down, could set a "haven't pulled a trial in xx min" in app.py, and shut down/stop an instance. should be able to run [this](https://docs.aws.amazon.com/cli/latest/reference/ec2/stop-instances.html) in the docker?

**Comment by antoinefalisse** [comment]
Existing API issue: https://github.com/stanfordnmbl/opencap-api/issues/56
