### ISSUE TITLE
Filter frequency gait

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-core#49]
@suhlrich 12Hz for fast gait (eg, sprinting) might be bad: https://github.com/stanfordnmbl/opencap-core/blob/main/main.py#L55.

We might want to consider making this an adjustable parameter at some point.

**Comment by suhlrich** [comment]
Yes. Probably makes most sense as a per-trial adjustment if we want to build out the "trial metadata" frontend.

Scott Uhlrich, PhD
Director of Research | Human Performance Lab
Bioengineering Department
Stanford University
<https://nmbl.stanford.edu/people/scott-uhlrich/>website<https://nmbl.stanford.edu/people/scott-uhlrich/>
________________________________
From: Antoine Falisse ***@***.***>
Sent: Monday, March 27, 2023 1:49 PM
To: stanfordnmbl/opencap-core ***@***.***>
Cc: Scott David Uhlrich ***@***.***>; Mention ***@***.***>
Subject: [stanfordnmbl/opencap-core] Filter frequency gait (Issue #49)


@suhlrich<https://github.com/suhlrich> 12Hz for fast gait (eg, sprinting) might be bad: https://github.com/stanfordnmbl/opencap-core/blob/main/main.py#L55.

We might want to consider making this an adjustable parameter at some point.

**Comment by antoinefalisse** [comment]
@suhlrich I want to add this. I am thinking of two things:
1. Add an option to select the filtering frequency at the session level (new option under advanced settings), which will apply to all trials except 2.
2. Add option to apply a specific frequency to a trial, can do when trial metadata infra is built in. This would overwrite 1., but I like having 1. so that you do it once and you can forget about it.
Let me know your thoughts

**Comment by suhlrich** [comment]
great idea. let's start at session level.
