### ISSUE TITLE
throw an error if nVideos != nVideos(calibration)

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-core#51]

**Comment by antoinefalisse** [comment]
How about we make this a slightly bigger piece and provide feedback on the frontend about upload status. We could add a color that would distinguish between uploading and processing. That being said, throwing an error would be very useful too.

**Comment by suhlrich** [comment]
Moved to https://github.com/stanfordnmbl/opencap-viewer/issues/78
