### ISSUE TITLE
person tracking for hrnet

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-core#94]
HRnet person tracking is less robust than OpenPose. Here's an example session (7ee78b97-5d3e-483c-ae68-142890a76b9d) where we get a sync failure with hrnet, which is likely a person tracking failure, but openpose works. @antoinefalisse do you mind looking into this sometime? Happy to hack it with you if you'd prefer.

**Comment by antoinefalisse** [comment]
Copying message from older issue:

The failures with this session 771b80d8-d423-4d69-98ac-e4071ca9a3a5 make me wonder if we have issues selecting the person to track when using hrnet. It was fixed when background people were gone. 3963a955-2b5d-421f-a2ac-3f8ff18d7cde.

Dig once local hrnet works.

**Comment by antoinefalisse** [comment]
Closing this one. @suhlrich keeps opening a new issue for this problem haha
