### ISSUE TITLE
openpose very slow locally on windows

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-core#97]
high res finally ran. first took a long time, others ran normal speed

![image](https://github.com/stanfordnmbl/opencap-core/assets/43877159/4d0395c7-520e-4401-8494-0d893da03250)

**Comment by suhlrich** [comment]
@antoinefalisse please add all the things you tried

**Comment by antoinefalisse** [comment]
What seems to work fine:
- Running service through WSL

What did not help:
- Updated cuda
- Downloaded fresh openpose
- Ran all updates on my machine

To try:
- try outside of opencap
